Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -14,10 +14,13 @@ jobs:
       matrix:
         should_fail: [false, true]
     continue-on-error: true
+    outputs:
+      test-failed: ${{ steps.check-test-failure.outputs.failed }}
     steps:
       - name: Echo matrix value
         run: echo "This matrix job should_fail=${{ matrix.should_fail }}"
       - name: Pass or fail
+        id: playwright-tests
         run: |
           if [ "${{ matrix.should_fail }}" = "true" ]; then
             echo "This job is designed to fail."
@@ -25,6 +28,15 @@ jobs:
           else
             echo "This job is designed to pass."
           fi
+      - name: Check if tests failed
+        id: check-test-failure
+        if: always()
+        run: |
+            if [[ "${{ steps.playwright-tests.outcome }}" == "failure" ]]; then
+                echo "failed=true" >> $GITHUB_OUTPUT
+            else
+                echo "failed=false" >> $GITHUB_OUTPUT
+            fi
 
   second_job_with_condition:
     needs: first_job
@@ -35,13 +47,12 @@ jobs:
       - name: Run if condition is met
         run: |
             echo "Second job with full condition completed."
-            echo "Outcome: ${{ steps.first_job.outcome }}"
 
-  fail_workflow_run_if_tests_failed:
-    needs: first_job
-    runs-on: ubuntu-latest
-    if: needs.first_job.result == 'failure' ||
-        needs.first_job.result == 'cancelled' ||
-        needs.first_job.result == 'skipped'
-    steps:
-      - run: exit 1
+  check-test-results:
+   if: always()
+   needs: first_job
+   runs-on: ubuntu-latest
+   steps:
+       - name: Fail if tests failed
+         run: |
+             [[ "${{ contains(needs.test.outputs.test-failed, 'true') }}" == "true" ]] && exit 1 || echo "All tests passed"
